;;; package --- Summary:
;;; Commentary:
;;; Lol
;;; Code:
(setq package-list '(
                     achievements
                     alchemist
                     apel
                     async
                     avy
                     bundler
                     calfw
                     cask
                     cask-mode
                     cider
                     clojure-mode
                     codesearch
                     coffee-mode
                     company
                     company-dict
                     company-inf-ruby
                     company-jedi
                     company-quickhelp
                     company-racer
                     concurrent
                     ctable
                     ctags
                     ctags-update
                     dash
                     deferred
                     dired+
		     ein
                     elixir-mode
                     elixir-yasnippets
                     elscreen
		     elpy
                     emmet-mode
                     epc
                     epl
                     expand-region
                     f
                     findr
                     flim
                     flycheck
                     flycheck-elixir
                     flycheck-rust
                     flymd
                     ggtags
                     git
                     git-commit
                     git-gutter
                     google-maps
                     goto-chg
                     haml-mode
                     helm
                     helm-ag
                     helm-git-grep
                     helm-core
                     helm-swoop
                     highlight-indentation
                     ht
                     htmlize
                     ibuffer-git
                     ibuffer-projectile
                     ibuffer-rcirc
                     ibuffer-tramp
                     ibuffer-vc
                     imenu-anywhere
                     imenu-list
                     inf-ruby
                     inflections
                     ivy
                     swiper
                     counsel
                     jump
                     js2-mode
                     json-mode
                     keyfreq
                     know-your-http-well
                     let-alist
                     macrostep
                     magit
                     magit-popup
                     markdown-mode
                     migemo
                     multiple-cursors
                     mustache
                     nav
                     neotree
                     nyan-mode
                     org
                     org-page
                     parent-mode
                     perspective
                     phoenix-dark-mono-theme
                     php-mode
                     pkg-info
                     popup
                     pos-tip
                     projectile
                     projectile-codesearch
                     projectile-rails
                     projectile-speedbar
                     python-environment
                     queue
                     racer
                     rake
                     rbenv
                     restclient
                     rich-minority
                     rinari
                     robe
                     rsense
                     rspec-mode
                     rubocop
                     ruby-additional
                     ruby-block
                     ruby-compilation
                     ruby-dev
                     ruby-hash-syntax
                     ruby-tools
                     rust-mode
                     rvm
                     s
                     sass-mode
                     scss-mode
                     semi
                     seq
                     simple-httpd
                     slime
                     slim-mode
                     smart-mode-line
                     smartparens
                     spinner
                     sr-speedbar
                     ssh
                     thrift
                     tracking
                     undo-tree
                     vimish-fold
                     web-mode
                     weechat
                     which-key
                     with-editor
                     xcscope
                     yaml-mode
                     yari
                     yasnippet
                     zenburn-theme))
(provide 'auto-install-packages)
;;; auto-install-packages.el ends here
