;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-skip-close-maybe
        sp-remove-active-pair-overlay
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        ))
