theme = "gruvbox-dark"
icons = "awesome"

[[block]]
block = "focused_window"
max_width = 30

[[block]]
block = "net"
device = "wlp3s0"
ssid = true
ip = true
speed_up = false
graph_up = true
interval = 5

[[block]]
block = "sound"

[[block]]
block = "backlight"

[[block]]
block = "battery"
interval = 10
device = "BAT1"
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d.%m %R"
